style: added updated styling
indykite/jarvis-sdk-web-sample-app-react pull request #17
Opened 2022-03-23 08:59 UTC by andskaal

2022-03-23 09:13 UTC, dusan-kovacik-profiq commented
I'm not able to select custom UI. Also, why is the page content not expanding more?
![image](https://user-images.githubusercontent.com/14073689/159664154-7ffc7129-c124-4d35-bbe5-5df327f48f0b.png)

2022-03-23 09:16 UTC, andskaal commented
> I'm not able to select custom UI. Also, why is the page content not expanding more?
> ![image](https://user-images.githubusercontent.com/14073689/159664154-7ffc7129-c124-4d35-bbe5-5df327f48f0b.png)

i am facing an issue where the screen goes white after selecting the custom UI, and Hana will help me troubleshoot this. I am aware of it, and sorry for not making that clear in the beginning 😄

2022-03-29 06:17 UTC, hanny21 requested changes
Looks good :tada: , but found few issues and left few comments:

1. when I select the `CZ` as language and refresh the page, the page is loaded with `EN`. this bug is introduced in this PR, works fine in deployed version.. probably you removed too much code? :thinking: 

2. there are always vertical and horizontal scrollbars visible even if there is no overflow.. looks really bad

4. when I load page for the first time, the container does not have minimum width, is that desired?
![image](https://user-images.githubusercontent.com/31318129/160545547-6cf75e92-488f-49cf-8b41-f53f60d92227.png)

2022-03-29 06:17 UTC, hanny21 commented on packages/web-ts/src/App.css
> +  fill: #FFF;
be consistent with the hex colors.. sometimes you are using lowercase and sometimes uppercase..

2022-03-29 06:17 UTC, hanny21 commented on packages/web-ts/src/App.tsx
> +  const handleOnUIUseChange = (type: any) => {
type of the param is `string`, so rather use `string` instead of `any`

2022-03-29 06:17 UTC, hanny21 commented on packages/web-ts/src/App.tsx
> +              <span className="selected-label">{renderDisplayLanguage()}</span>
would be good to be consistent how you assign conditional classNames.. looks weird if it is not done same in same file..

`{state === "built-in" ? "selected":""}`
`${langToggled && "toggled"}`

2022-03-29 06:17 UTC, hanny21 commented on packages/web-ts/src/assets/arrow-down.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><!--! Font Awesome Pro 6.1.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Cop
linter error at the end of the file, please fix it

2022-03-29 12:32 UTC, hanny21 commented on packages/web-ts/package.json
> +    "fix:prettier": "prettier --loglevel warn --write ."
the eslint script not working

2022-03-29 12:42 UTC, hanny21 approved these changes

2022-03-30 09:05 UTC, dusan-kovacik-profiq approved these changes

2022-03-30 09:29 UTC, merged