fix: added 16% test coverage
indykite/jarvis-sdk-web-sample-app-react pull request #21
Opened 2022-03-30 10:40 UTC by andskaal

2022-03-30 10:47 UTC, maprokes commented on packages/web-ts/package.json
> +    "coverage": "^0.4.1",
I don't see the coverage being used

2022-03-30 11:20 UTC, hanny21 requested changes
hi, looking good.. please just change 1 mock and also resolve all formatting issues as well

2022-03-30 11:20 UTC, hanny21 commented on packages/web-ts/package.json
> +    "lint:prettier": "prettier --check ."
we do not need `eject` script - once we eject there is no way back :cry: 
the scripts related to `eslint` and `prettier` will probably not work.
please keep only the `coverage` and `coverage-ci` scripts or make sure that all others work if you put them here

2022-03-30 11:20 UTC, hanny21 commented on packages/web-ts/src/__test__/Login.test.js
> +                Promise.resolve({
just use `Promise.resolve()`.. if you check the signature for the `renderLogin` function, you would see that it returns void.

2022-03-31 08:15 UTC, hanny21 commented on packages/web-ts/package.json
> +    "lint": "run-s lint:*"
is `yarn lint` working for you? I am getting an error.. probably because the lint is not installed for typescript project.. for new can you remove the script?

2022-03-31 08:28 UTC, hanny21 approved these changes

2022-03-31 08:28 UTC, merged