chore: upgrade packages
indykite/jarvis-sdk-web-sample-app-react pull request #34
Opened 2022-06-02 12:30 UTC by minasjam

https://app.clickup.com/t/36057148/IK-2638

I upgraded all I thought reasonable, but I am as unsure as I can be, whether I did all I should have. Please have a look and let me know.

Also, Cypress works locally but not here :-/ It tells me that useNavigate is not exported from react-router-dom, but it should be with the version I have in. Wierd :-/ Anyone could point me to how to fix that?

2022-06-03 08:30 UTC, dusan-kovacik-profiq requested changes

2022-06-03 08:30 UTC, dusan-kovacik-profiq commented on packages/web-ts/src/components/SetNewPassword.tsx
> +      token: referenceId || "",
Maybe it would be better to check whether the `referenceId` is defined before you call `IKUICore.renderSetNewPasswordForm`. Because in that case it's useless to call it.

2022-06-03 08:30 UTC, dusan-kovacik-profiq commented on packages/web-ts/src/components/custom/CustomSetNewPassword.tsx
> +    IKUIUserAPI.sendNewPassword(referenceId || "", newPassword)
Here the same. Check whether `referenceId` is defined before you call `IKUIUserAPI.sendNewPassword`.

2022-06-03 08:30 UTC, dusan-kovacik-profiq commented on packages/web/package.json
> +    "react-scripts": "^5.0.1"
You forgot to update `react-router-dom` package. That's probably the reason why the cypress tests are failing.

2022-06-03 10:25 UTC, minasjam commented on packages/web/package.json
> +    "react-scripts": "^5.0.1"
updated up to web-ts version

2022-06-06 05:05 UTC, minasjam commented
@hanny21  @dusan-kovacik-profiq Per instructions I have updated packages in web-ts. 

I have also fixed cypress tests and updated the PR rules so that cypress checks web-ts in the pipeline. @kilimandzsaro please have a look at it.

2022-06-06 05:22 UTC, hanny21 requested changes
left you few comments... also is there any reason why we cannot use latest react version, e.g. version 18? if so, would be nice to document it findings in the task you have

2022-06-06 05:22 UTC, hanny21 commented on packages/web-ts/package.json
> +    "react-router-dom": "^6.3.0",
just wondering why we are not using the same version of `react-router` and `react-rouer-dom`? since `react-router-dom` contains everything what `router-router` does and has dependecy to it.

2022-06-06 05:22 UTC, hanny21 commented on packages/web-ts/package.json
> +    "@types/node": "17.0.23",
please put all types into dev dependencies together with typescript

2022-06-06 05:22 UTC, hanny21 commented on packages/web-ts/.env-wonka
> +REACT_APP_BASE_URI=https://jarvis-dev.indykite.com
we should not commit any `.env` file.. if needed put it into `.gitignore`.. but we do not want to expose any credentials in public repo :wink:

2022-06-09 10:20 UTC, minasjam commented
Hi @hanny21 @dusan-kovacik-profiq @kilimandzsaro , 
As the commit suggest the following has been done: 

- packages are updated
- cypress has been updated to v.10, tests have been fixed, dashboard has been added to PR, the pipeline now checks web-ts - big thanks to @kilimandzsaro for working on this and supporting me
- a workaround the double run of useeffect has been added

Please have a look, I have been at it for a bit too long, so I might have missed stuff.

2022-06-09 13:03 UTC, kilimandzsaro approved these changes
Good job! 👍

2022-06-09 17:16 UTC, hanny21 approved these changes
looks good :+1: , left just few comments..
I am also thinking about that double render problem... the workaround works, but look weird and I do not know what you think.. I am still undetermined which approach is the best (like I think one then after few hours I find argument agains)... now I am half day convinced that maybe that workaround is not sth we need ,because it will be just in development.. maybe we should just run the cypress tests against different environment? what do you think @kilimandzsaro ? I am not sure if it is just possible to set the node environment for the application running in cypress to something else that development (which might do the trick)

2022-06-09 17:16 UTC, hanny21 commented on packages/web-ts/src/components/custom/CustomLogin.tsx
> +    (data: any) => {
please do not use `any`, but assign correct type

2022-06-09 17:16 UTC, hanny21 commented on packages/web-ts/src/components/custom/CustomRegistration.tsx
> +    (data: any) => {
please do not use `any`, but assign correct type

2022-06-09 17:16 UTC, hanny21 commented on packages/web-ts/src/components/custom/CustomRegistration.tsx
> +      console.log("Custom Registration");
remove

2022-06-10 06:30 UTC, minasjam commented
> looks good +1 , left just few comments.. I am also thinking about that double render problem... the workaround works, but look weird and I do not know what you think.. I am still undetermined which approach is the best (like I think one then after few hours I find argument agains)... now I am half day convinced that maybe that workaround is not sth we need ,because it will be just in development.. maybe we should just run the cypress tests against different environment? what do you think @kilimandzsaro ? I am not sure if it is just possible to set the node environment for the application running in cypress to something else that development (which might do the trick)

2022-06-10 06:30 UTC, closed without merging

2022-06-10 07:05 UTC, kilimandzsaro commented
@hanny21 the tests runs against a local application what the test spins up. It's because it's using the latest code to test. It is easy to setup to run the test against a different environment, just need to setup the new baseUrl. Is this double rendering happens only when the app was spin up locally or it happens all the time? I think the double render by default is not nice and can be annoying. But, if we can determine an element which will be loaded the last on the page (and not part of the double render elements), then we can add a check to the tests to wait for that element. With this we maybe able to avoid the test failures. If there is such an element.

2022-06-13 10:15 UTC, dusan-kovacik-profiq approved these changes
Honestly, I don't like the workaround as it's on too many places - couldn't it be somehow moved just to one hook where the workaround would be applied? Anyway, we probably want to finish this task asap, so I'm giving you the approval, but we shouldn't keep the workaround in the current state :/

2022-06-13 10:15 UTC, dusan-kovacik-profiq commented on packages/web-ts/src/App.tsx
> +    };
I think you don't need to care about the double rendering in this component as the `useEffect` calls the init function only and the function only sets some global variables.

2022-06-13 10:24 UTC, minasjam commented on packages/web-ts/src/App.tsx
> +    };
We will look at the workaround with @hanny21 once more in Wednesday.. Hopefully we will get rid of it and set the Cypress tests to run not on dev :-)

2022-07-13 12:11 UTC, minasjam commented
These last commits should fulfill the task [IK-3409](https://app.clickup.com/t/36057148/IK-3409) which will free me up to finish the original task.

2022-07-13 12:13 UTC, minasjam commented on packages/web-ts/src/App.tsx
> +    };
Hi Dušan, 
So, the workaround has been reverted :-)

2022-07-13 12:15 UTC, hanny21 approved these changes
:+1:

2022-07-13 12:15 UTC, hanny21 commented on packages/web-ts/.gitignore
> +yarn-error.log*
please fix :wink:

2022-07-13 12:16 UTC, hanny21 commented
@minasjam also please can you rebase the branch? maybe too many commits... this is public repo, so make sure that git history looks good :wink:

2022-07-13 13:17 UTC, dusan-kovacik-profiq commented on packages/web-ts/src/components/custom/CustomLogin.tsx
> +    (data: DataTokenResponseType | Error) => {
`data` can also have an `Error` type?