chore: deprecate web-simple and web sample app
indykite/jarvis-sdk-web-sample-app-react pull request #79
Opened 2022-09-05 12:05 UTC by wmcheung

- Removes web and web-simple from packages
- Updated README with a section for people to find the commit where web & web-simple still functioned.
- Update jarvis-sdk-web dependency to v0.2.3

Linked task: https://github.com/indykite/jarvis-backlog/issues/346

2022-09-05 14:13 UTC, maprokes reviewed
@wmcheung adding my 2 cents

2022-09-05 14:13 UTC, maprokes commented on packages/web-ts/.env-example
> +REACT_APP_BASE_URI=
I think that we wanted to keep these env values in place so users has fully working example app after cloning.

2022-09-05 14:13 UTC, maprokes commented on packages/web/.env-wonka
> -REACT_APP_BASE_URI=https://jarvis-dev.indykite.com
this files is used in deployment pipeline for the wonka deployment, we should either move it to web-ts and adjust the pipeline, or add it as secret and inject it into the pipeline as secret https://github.com/indykite/jarvis-sdk-web-sample-app-react/blob/master/.github/workflows/dev-build-deploy.yaml#L42

the same applies for .env-wonka-stg

2022-09-05 14:21 UTC, wmcheung commented on packages/web/.env-wonka
> -REACT_APP_BASE_URI=https://jarvis-dev.indykite.com
Yes, I see that cypress is failing because of this file.

Wrote the same thought in the #team-engineering-questions-answers channel, with the steps I want to take to fix this. Injecting the secrets into the pipeline is a necessary step to eliminate hard-coded credentials from this repo.

2022-09-05 14:27 UTC, maprokes commented on packages/web/.env-wonka
> -REACT_APP_BASE_URI=https://jarvis-dev.indykite.com
I don't think that the appId and tenantId are considered confidential, as they are anyway plaintext readable in the app source code. So I don't see a strong not to keep them as part of the source code, what do you think?

2022-09-06 07:13 UTC, minasjam approved these changes
LGTM :+1:

2022-09-06 08:23 UTC, wmcheung commented
@chikodich knows where the break is in cypress, she will help out on resolving it.

2022-09-06 08:30 UTC, chikodich commented
Cypress test failing at
✖ homepage.cy.js - element not found
✖ login.cy.js - outdated path?

Login check test is currently being rewritten, will also rewrite homepage tests

2022-09-15 12:14 UTC, kilimandzsaro requested changes

2022-09-15 12:14 UTC, kilimandzsaro commented on yarn.lock
> +=======
@wmcheung Please remove the lines from merge conflicts :)

2022-09-15 12:14 UTC, kilimandzsaro commented on yarn.lock
> +<<<<<<< HEAD
@wmcheung Please remove the lines from merge conflicts :)

2022-09-15 12:14 UTC, kilimandzsaro commented on yarn.lock
> +>>>>>>> a3c4881c3bf170e5c54c1235886435a44caf8247
@wmcheung Please remove the lines from merge conflicts :)

2022-09-15 12:15 UTC, wmcheung commented on yarn.lock
> +>>>>>>> a3c4881c3bf170e5c54c1235886435a44caf8247
thought i fixed the merge conflicts, good find thanks!

2022-09-15 12:18 UTC, wmcheung commented on yarn.lock
> +>>>>>>> a3c4881c3bf170e5c54c1235886435a44caf8247
I fixed it but forgot to push 😄 should be fine now!

2022-09-16 08:26 UTC, chikodich approved these changes
good to go

2022-09-16 08:26 UTC, kilimandzsaro approved these changes

2022-09-16 09:18 UTC, merged