create user tests
indykite/jarvis-sdk-web-sample-app-react pull request #87
Opened 2022-10-11 11:44 UTC by chikodich

create new user tests, 
login/ logout functions,
login tests edits

2022-10-11 15:27 UTC, kilimandzsaro requested changes

2022-10-11 15:27 UTC, kilimandzsaro commented on cypress/integration/create-user.cy.js
> +    cy.task("getTestUsername").then((testUsername) => {
This variable is set in the previous step, so this test is not independent. (see previous comment)

2022-10-11 15:27 UTC, kilimandzsaro commented on cypress/integration/create-user.cy.js
> +    cy.task("getTestUsername").then((testUsername) => {
This variable is created in a test before this, so this test is not independent anymore. (see previous comment)

2022-10-11 15:27 UTC, kilimandzsaro commented on cypress/integration/create-user.cy.js
> +    cy.task("getTestUsername").then((testUsername) => {
This variable is created in a test before this, so this test is not independent anymore. (see previous comment)

2022-10-11 15:27 UTC, kilimandzsaro commented on cypress/support/commands.js
> +      headers: { "Content-Type": "text/plain" },
Why it is not "application/json"?

2022-10-11 15:27 UTC, kilimandzsaro commented on cypress/support/commands.js
> +Cypress.Commands.add('logoutExistingUser', (username, password) => {
Not to repeat yourself, you can return the `token` and `refresh_token` in the `loginExistingUser` method and just call that method before you logout the user. This seems a code duplication.

2022-10-11 15:27 UTC, kilimandzsaro commented on cypress/support/commands.js
> +      headers: { "Content-Type": "text/plain" },
why is it not "application/json"? You are sending a json object in the body.

2022-10-11 15:27 UTC, kilimandzsaro commented on cypress/support/commands.js
> +      headers: { "Content-Type": "text/plain" },
Why it's not an `application/json`

2022-10-11 15:27 UTC, kilimandzsaro commented on cypress/support/commands.js
> +    expect(resp.body == {});
you can expect that the `resp.status === 200` instead of an empty body

2022-10-11 15:27 UTC, kilimandzsaro commented on cypress/support/steps/createUser.js
> +  //   }
You can remove the commented section

2022-10-11 15:27 UTC, kilimandzsaro commented on cypress/support/steps/createUser.js
> +    CreateUserEls.newUsernameInput.type(username, { force: true });
You can chain this together or is it not working that way?
CreateUserEls.newUsernameInput.clear({ force: true }).type(username, { force: true });

2022-10-11 15:27 UTC, kilimandzsaro commented on cypress/support/steps/createUser.js
> +    CreateUserEls.passwordInput.type(password, { force: true });
You can chain this together or is it not working that way?
CreateUserEls.passwordInput.clear({ force: true }).type(username, { force: true });

2022-10-11 15:27 UTC, kilimandzsaro commented on cypress/support/steps/createUser.js
> +    CreateUserEls.confirmPasswordInput.type(password, { force: true });
You can chain this together or is it not working that way?
CreateUserEls.confirmPasswordInput.clear({ force: true }).type(username, { force: true });

2022-10-11 15:27 UTC, kilimandzsaro commented on cypress/integration/create-user.cy.js
> +    CreateUserAssertions.confirmPasswordIsRendered();
You can use 1 assertion which checks these 3 things. No need to check it one-by-one in the test.
Eg.:
the following function can be in the `CreatUserAssertions` file
```js
createAccountFormIsRendered() {
  this.usernameInputIsRendered();
  this.passwordInputIsRendered();
  this.confirmPasswordIsRendered();
}
```

2022-10-13 18:37 UTC, chikodich commented on cypress/integration/create-user.cy.js
> +    cy.task("getTestUsername").then((testUsername) => {
updated - moved to before block

2022-10-13 18:38 UTC, chikodich commented on cypress/integration/create-user.cy.js
> +    cy.task("getTestUsername").then((testUsername) => {
updated - defined in before block

2022-10-13 18:39 UTC, chikodich commented on cypress/support/commands.js
> +      headers: { "Content-Type": "text/plain" },
was using an auto-generated header - upadated to "application/json"

2022-10-13 18:41 UTC, chikodich commented on cypress/support/commands.js
> +Cypress.Commands.add('logoutExistingUser', (username, password) => {
updated - logoutExistingUser calls loginExistingUser. Had to define loginExistingUser as a normal function and wrap the token values to be able to return them.

2022-10-13 18:41 UTC, chikodich commented on cypress/support/steps/createUser.js
> +  //   }
updated -removed

2022-10-13 18:42 UTC, chikodich commented on cypress/support/commands.js
> +      headers: { "Content-Type": "text/plain" },
was using an auto-generated header - upadated to "application/json"

2022-10-13 18:43 UTC, chikodich commented on cypress/support/commands.js
> +      headers: { "Content-Type": "text/plain" },
was using an auto-generated header - upadated to "application/json"

2022-10-13 18:43 UTC, chikodich commented on cypress/support/commands.js
> +    expect(resp.body == {});
updated to resp.status === 200

2022-10-13 18:44 UTC, chikodich commented on cypress/integration/create-user.cy.js
> +    CreateUserAssertions.confirmPasswordIsRendered();
updated - defined createAccountFormIsRendered()

2022-10-13 18:44 UTC, chikodich commented on cypress/integration/create-user.cy.js
> +    cy.task("setTestUsername", testUsername);
updated - moved to before block

2022-10-13 18:45 UTC, chikodich commented on cypress/support/steps/createUser.js
> +    CreateUserEls.newUsernameInput.type(username, { force: true });
Tried chaining originally - it throws a detached from DOM error. Had to separate

2022-10-13 18:46 UTC, chikodich commented on cypress/support/steps/createUser.js
> +    CreateUserEls.confirmPasswordInput.type(password, { force: true });
Tried chaining originally - it throws a detached from DOM error. Had to separate

2022-10-14 08:00 UTC, kilimandzsaro commented on cypress/support/commands.js
> +    const refreshToken = tokens.refreshToken;
Just a comment: you don't have to define separately these two variables, but you can use the `token.token` and `token.refreshToken` directly in line 139 and 141.

2022-10-14 08:01 UTC, kilimandzsaro commented on cypress/support/steps/createUser.js
> +    CreateUserEls.newUsernameInput.type(username, { force: true });
Yeh, with react it happens, that's why I asked :D

2022-10-14 08:01 UTC, kilimandzsaro commented on cypress/support/steps/createUser.js
> +    CreateUserEls.passwordInput.type(password, { force: true });
Yeh, with react it happens, that's why I asked :D

2022-10-14 08:01 UTC, kilimandzsaro commented on cypress/support/steps/createUser.js
> +    CreateUserEls.confirmPasswordInput.type(password, { force: true });
Yeh, with react it happens, that's why I asked :D

2022-10-14 12:33 UTC, chikodich commented on cypress/support/commands.js
> +    const refreshToken = tokens.refreshToken;
updated to token.token and token.refreshToken

2022-10-14 12:45 UTC, chikodich commented on cypress/integration/create-user.cy.js
> +    LoginAssertions.authenticationSuccessful();
The submit button points at a strictly createUser element/action [or only exposed when a user attempts to create a new account] but the login button was already defined in the login test and was only used to confirm that creating a new user had actually worked. -- is this logical or should I create CreateUserSteps.clickLoginButton()?

2022-10-14 12:46 UTC, chikodich commented on cypress.config.js
> +          return (secondUsername = val)
updated - let secondUsername defined in cypress.config.js

2022-10-14 13:06 UTC, kilimandzsaro approved these changes

2022-10-14 13:16 UTC, merged